name: Run Robocop

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install robotframework-robocop

      - name: Run robocop and generate SARIF output
        run: |
          mkdir -p reports
          python -m robocop --report sarif . || true

      - name: List files in current directory (debugging step)
        run: ls -la

      - name: Output SARIF file for inspection
        run: cat .sarif.json

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: .sarif.json
          category: robocop
