name: Run Robocop

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # continue even if Robocop returns issues and fails step
    continue-on-error: true
    permissions:
      # required for issues to be recorded
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework-robocop
      - name: Run robocop and generate SARIF output
        run: |
          mkdir -p reports
          python -m robocop --reports sarif --output reports/robocop-output.sarif . || true

      - name: List files in reports directory (debugging step)
        run: ls -la reports

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: reports/robocop-output.sarif
          category: robocop